ServiceMax-Engineering/create-react-app

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
- Added bower_components to sass loader include paths
- Added babel plugin config for webpack prod
=> Few webpack fixes for css and babel

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/package.json
* Update wepack sass settings to let @svmx/ui-component-library sass imports works
* Update incorrect eslint-plugin-jsx-a11y version due to conflicts with eslint-config-react-app
@joshsylvester pls help review.
=> MAX-5115 Fix ui-components-predix sass and bower issue.

package.json, packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/template/public/index.html
* Update webpack configuration for loading polymer elements.
* Update public/index.html to include Polymer polyfills.
@joshsylvester pls help review.
=> MAX-5108 React Polymer Integration

packages/react-scripts/template/src/components/APICall/APICall.js, packages/react-scripts/template/src/components/APICall/APICall.test.js, packages/react-scripts/template/src/components/APICall/index.js, packages/react-scripts/template/src/containers/AppContainer/AppContainer.js
Added APICall component with call and testing
=> UI-12 Simple API Call on componentWillMount hook

packages/react-scripts/template/public/index.html
* Update index template to work with Polymer 2.X.
@joshsylvester pls help review.
=> MAX-5276, MAX-5494 Fix predix component lazy-load/dynamic creation issue

packages/react-scripts/package-lock.json
It's caused by **npm install** failed. I just remove the old `package-lock.json` file and reinstall again, the **npm install** works well now.
@joshsylvester , please review.
=> MAX-5628 Create-React-App-Auto-Publish job failed

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
* Re-factor webpack configuration to seperate configuration for with/with-out ui-compoennts-predix. (Fix MAX-5221#1)
* Update webpack prod configuration to copy bower_components from node_modules/@svmx/ui-components-predix/build folder
@joshsylvester pls help review.
=> MAX-5440 Optimize build process for ui-components-predix

packages/react-scripts/template/.template.dependencies.json, packages/react-scripts/template/src/actions/APICall.Test.js, packages/react-scripts/template/src/actions/APICall.js, packages/react-scripts/template/src/components/APICall/APICall.js, packages/react-scripts/template/src/components/APICall/APICall.test.js, packages/react-scripts/template/src/components/AppHello/AppHello.js, packages/react-scripts/template/src/components/AppHello/AppHello.test.js, packages/react-scripts/template/src/containers/APICallContainer/APICallContainer.js, packages/react-scripts/template/src/containers/APICallContainer/APICallContainer.test.js, packages/react-scripts/template/src/containers/APICallContainer/index.js, packages/react-scripts/template/src/containers/AppContainer/AppContainer.test.js
https://servicemax.atlassian.net/browse/UI-183
=> UI-183 - CRA  more coverage and clean up

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/package-lock.json, packages/react-scripts/package.json, packages/react-scripts/template/public/index.html, packages/react-scripts/template/src/actions/SFCall.js, packages/react-scripts/template/src/components/APICall/APICall.js, packages/react-scripts/template/src/components/Hello/Hello.js, packages/react-scripts/template/src/components/Hello/Hello.scss
* salesforce assets copying to `/assets/`
* salesforce UI compiling via sass dynamically
* ONLY DEV environment is setup.
* fonts are still not loading on CRA.
TO USE
1. rename the package for `CRA/packages/react-scripts` in `package.json` to "react-scripts-name"
2. `npm publish`
3. build a new app with `create-react-app --scripts-version=@svmx/react-scripts-name sf-proj`
4. `npm install --save @svmx/ui-components-lightning` (somehow we need to install the branch that is at this code review: https://github.com/ServiceMax-Engineering/ui-components-lightning/pull/40)
4. edit `/src/index.js` to add this line `import '@svmx/ui-components-lightning/lib/package.scss';`
5. edit `src/components/Hello/Hello.js` to use lightning components. 
```
import { Button, Input } from …
```
=> UI-994 changes to webpack and UI to get salesforce working 

packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/package.json
* Production webpack build got same changes as development build.
To test in the meantime before this is merged:
```
create-react-app --scripts-version=@svmx/react-scripts-josh tmp-webpack-production
```
=> UI-1017 updated production build to work with lightning

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/package-lock.json, packages/react-scripts/package.json, packages/react-scripts/scripts/init.js, packages/react-scripts/template/public/index.html, packages/react-scripts/template/src/actions/SFCall.js, packages/react-scripts/template/src/components/APICall/APICall.test.js, packages/react-scripts/template/src/node/app.js
* Updated both *production* and *development* webpack configurations
* Updated `template/index.html` file to properly include the needed files for local and production development
=> UI-1047 Updates to CRA for ui-lightning

packages/react-scripts/config/webpack.config.prod.js
replacing [contenthash.8] with the proper [chunkhash.8] for the js filename.
=> UI-1066 minor fix to CRA from CR

packages/react-scripts/package.json, packages/react-scripts/template/.eslintrc.json, packages/react-scripts/template/.template.dependencies.json, packages/react-scripts/template/src/actions/APICall.test.js, packages/react-scripts/template/src/actions/SFCall.test.js, packages/react-scripts/template/src/components/APICall/APICall.js, packages/react-scripts/template/src/components/APICall/APICall.test.js, packages/react-scripts/template/src/components/AppHello/AppHello.scss, packages/react-scripts/template/src/containers/APICallContainer/APICallContainer.test.js, packages/react-scripts/template/src/containers/AppContainer/AppContainer.test.js, packages/react-scripts/template/src/containers/SFAPICallContainer/SFAPICallContainer.test.js, packages/react-scripts/template/src/node/app.js, packages/react-scripts/template/src/node/app.test.js, packages/react-scripts/template/src/node/server.js, packages/react-scripts/template/src/node/server.test.js
* added eslint rule for multiple line breaks
* fixed all lint errors
* fixed related tests
* fixed all lint-style errors.
=> UI-1174 adding no-multiple-lines to eslint, fixed all tests

packages/react-scripts/package.json, packages/react-scripts/template/.eslintrc.json, packages/react-scripts/template/.stylelintrc, packages/react-scripts/template/src/App.js, packages/react-scripts/template/src/actions/APICall.js, packages/react-scripts/template/src/actions/APICall.test.js, packages/react-scripts/template/src/actions/SFCall.js, packages/react-scripts/template/src/actions/SFCall.test.js, packages/react-scripts/template/src/actions/hello.js, packages/react-scripts/template/src/actions/hello.test.js, packages/react-scripts/template/src/components/APICall/APICall.js, packages/react-scripts/template/src/components/AppHello/AppHello.js, packages/react-scripts/template/src/containers/AppContainer/AppContainer.test.js, packages/react-scripts/template/src/node/app.js, packages/react-scripts/template/src/node/app.test.js, packages/react-scripts/template/src/node/server.js, packages/react-scripts/template/src/registerServiceWorker.js, packages/react-scripts/template/src/store/index.js, packages/react-scripts/template/src/store/loading.js, packages/react-scripts/template/src/store/loading.test.js, packages/react-scripts/template/src/store/middleware.js, packages/react-scripts/template/src/store/reducer.js, packages/react-scripts/template/src/test/jest-setup.js, packages/react-scripts/template/src/test/mock-store.js, packages/react-scripts/template/src/theme/index.scss, packages/react-scripts/template/src/utils/index.js
- re-ordered the eslint config file for easier diffing
- added eslint sort-props
- added stylelint config settings
- fixed all files within _react-scripts_ to match above rules
=> UI-1664 eslint sort-keys & stylelint upgrades

packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/template/src/components/AppHello/AppHello.js, packages/react-scripts/template/src/index.js
- minor issue with helloWorld and new exports.
- committed merge conflict in production build file.
=> UI-1877 minor fixes to CRA to fix regressions.

packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/template/public/index.html
minor change to CreateReactApp to allow public_url to be passed into the application
=> UI-2422 pass public_url to application

packages/react-scripts/config/webpack.config.prod.js
argh! one last change
note: this will break existing builds in a small way - we will be doing a version change.
=> UI-2422 minor change to public path for demo server.

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
minor updates to paths, and comments to make webpack config more legible
=> UI-2422 minor updates to paths for local assets.

packages/react-scripts/package.json, packages/react-scripts/scripts/salesforce.js
- Automatically create zip file as part of sf-build
=> UI-1281 updated salesforce build to create zip file

packages/react-scripts/package-lock.json, packages/react-scripts/package.json
=> UI-2735 add raw-loader for custom images

packages/react-scripts/config/webpack.config.dev.js
- changing the location to look for salesforce assets back to the original location
=> UI-3007 Salesforce asset location fix

README.md
Update the Read me with the Node and npm version we are testing our app on.
=> Node npm version on readme

packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/config/webpack.config.staging.js
* Apply svg support to prod/stage envs.
@joshsylvester @elvinfucom @vincentcn @benjaminliugang pls help review.
=> MAX-13475 SB: Kabob icon is not shown on gantt chart in latest build

packages/react-scripts/template/public/index.html
- minor change to add `%PUBLIC_URL%` to css and js file paths.
=> UI-3470 minor change to index.html

packages/react-scripts/config/webpack.config.prod.js
* Add SOURCEMAP_URL setting to support private source maps.
@elvinfucom @joshsylvester @benjaminliugang @vincentcn pls help review.
=> MAX-10725 Enable UI source mapping at production

packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/package-lock.json, packages/react-scripts/package.json, packages/react-scripts/template/public/index.cmp, packages/react-scripts/template/public/index.html, packages/react-scripts/template/public/index.vfp, packages/react-scripts/template/public/indexController.js, packages/react-scripts/template/public/manifest.json, packages/react-scripts/template/src/actions/SFCall.js
- Enable projects to be deployed on to the _Salesforce_ lightning container/platform
- The project should include env variable `IS_TARGETPAGE_LIGHTNING` set to `true`
- Should include SLDS styles manually generated and uploaded on to static resource before the build(will be automated soon)
=> UI-4231: Research deploying React project into Lightning Component container

packages/react-scripts/template/.env.production, packages/react-scripts/template/public/index.html
- Prepare template specific to lightning vs vfpage deployable
- Added base `.env.production` config file
=> UI-2624, UI-4623: Prepare template specific to lightning vs vfpage

packages/react-scripts/template/public/index.html
- Minor fix to distribution bundle needed both in dev and production builds
=> UI-4624: Distribution bundle needed both in dev and production builds

packages/react-scripts/package.json, packages/react-scripts/template/.template.dependencies.json, packages/react-scripts/template/src/Routes.test.js, packages/react-scripts/template/src/actions/SFCall.test.js, packages/react-scripts/template/src/containers/SFAPICallContainer/SFAPICallContainer.test.js, packages/react-scripts/template/src/services/ServiceRequest.test.js, packages/react-scripts/template/src/services/service.test.js, packages/react-scripts/template/src/store/middleware.test.js
Upgrade enzyme and jest
Had to ignore test as they have been failing even before the upgrade
https://servicemax.atlassian.net/browse/UI-4745
Also I have a few questions
Should i do a version change  on package.json?
=> UI-4470  jest - enzyme version change

packages/react-scripts/config/libs.js, packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js
* Add support for resolving the components at @svmx/war-ui-components.
* Add support for dynamic predix path.
@elvinfucom @benjaminliugang pls help review.
=> WAR-42 WAR-58 WAR UI and jenkins job Setup

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/config/webpack.config.staging.js, packages/react-scripts/package-lock.json, packages/react-scripts/package.json
https://servicemax.atlassian.net/browse/GCON-205
We will be using typescript in our GCON app. This PR adds a minimal configuration to our webpack config files to support  `ts` and `tsx` extensions.
=> GCON-205 - Add typescript to GCON app

packages/react-scripts/config/alias.js, packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/config/webpack.config.staging.js
* Add webpack alias support for fixing npm link issue when using react hooks.
* See these links for more detail.
** https://github.com/facebook/react/issues/13991
** https://github.com/facebook/create-react-app/issues/2188
** https://github.com/facebook/create-react-app/pull/3554
@elvinfucom @benjaminliugang pls help review.
=> MAX-20403 Adopt react hooks

packages/react-scripts/config/webpack.config.dev.js, packages/react-scripts/config/webpack.config.prod.js, packages/react-scripts/config/webpack.config.staging.js
* Support get env variable in sass. Need use env variable to set the right font url - stage/prod.
@elvinfucom @benjaminliugang @haoruiqian pls help review.
=> MAX-24172 Replace predix-ui GE Font CDN
